language: node_js # 设置语言
node_js: stable # 设置相应版本
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限
install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "yonichens"
    - git config user.email "yonichens@hotmail.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
branches:
    only:
        - hexo # 只监测hexo分支
env:
    global:
        - GH_REF: github.com/yonichens/yonichens.github.io.git #设置GH_REF，注意更改成自己的仓库地址
